//! Real Redis/TiKV publication contracts using the existing public API fixtures.
//! Transport response loss and GC races require separate integration tests.

use std::collections::BTreeSet;

use super::*;

enum PublicationContract {
    SameHeadRetry,
    ExpandUnissuedRange,
    RejectIssuedIds,
}

async fn cleanup_namespace(url: &str, namespace: &str) {
    // This namespace is generated by the test, never supplied by the caller.
    assert!(namespace.starts_with("g12-real-"));
    let prefix = format!("{{brewfs-ws-v1}}:{namespace}:ws:v1/").into_bytes();
    let mut pattern = prefix.clone();
    pattern.push(b'*');
    let client = redis::Client::open(url).unwrap();
    let mut connection = client.get_multiplexed_async_connection().await.unwrap();
    let mut cursor = 0_u64;
    let mut keys = BTreeSet::new();
    loop {
        let (next, batch): (u64, Vec<Vec<u8>>) = redis::cmd("SCAN")
            .arg(cursor)
            .arg("MATCH")
            .arg(&pattern)
            .arg("COUNT")
            .arg(256_u32)
            .query_async(&mut connection)
            .await
            .unwrap();
        for key in batch {
            assert!(key.starts_with(&prefix), "cleanup escaped its namespace");
            keys.insert(key);
        }
        cursor = next;
        if cursor == 0 {
            break;
        }
    }
    if !keys.is_empty() {
        let deleted: usize = redis::cmd("DEL")
            .arg(keys.iter().collect::<Vec<_>>())
            .query_async(&mut connection)
            .await
            .unwrap();
        assert_eq!(deleted, keys.len());
    }
}

async fn real_redis_publication_contract(contract: PublicationContract) {
    let budget = V3MountBudget::defaults();
    let url = std::env::var("BREWFS_TEST_REDIS_URL")
        .expect("BREWFS_TEST_REDIS_URL must point at an isolated Redis");
    let namespace = format!("g12-real-{}", Uuid::new_v4().simple());
    let backend = RedisWorkspaceBackend::connect(&url, &namespace)
        .await
        .unwrap();
    let store = KvWorkspaceStore::new(backend).with_packed_reader_pin_budget(budget);
    // Join captures assertion panics so cleanup still runs after a failure.
    let outcome = tokio::spawn(async move {
        match contract {
            PublicationContract::SameHeadRetry => publish_same_head(&store).await,
            PublicationContract::ExpandUnissuedRange => {
                publication_inode_expansion_reserves_unissued_range(&store).await;
            }
            PublicationContract::RejectIssuedIds => {
                publication_inode_expansion_rejects_issued_ids(&store).await;
            }
        }
    })
    .await;
    cleanup_namespace(&url, &namespace).await;
    outcome.expect("real Redis publication contract failed");
}

async fn real_tikv_publication_contract(contract: PublicationContract) {
    let budget = V3MountBudget::defaults();
    let endpoints = std::env::var("BREWFS_TEST_TIKV_PD_ENDPOINTS")
        .expect("BREWFS_TEST_TIKV_PD_ENDPOINTS must point at an isolated TiKV cluster")
        .split(',')
        .map(str::to_owned)
        .collect();
    let namespace = format!("g12-real-{}", Uuid::new_v4().simple());
    let backend = TiKvWorkspaceBackend::connect_with_budget(endpoints, &namespace, budget.clone())
        .await
        .unwrap();
    let cleanup = backend.clone();
    let store = KvWorkspaceStore::new(backend).with_packed_reader_pin_budget(budget);
    let outcome = tokio::spawn(async move {
        match contract {
            PublicationContract::SameHeadRetry => publish_same_head(&store).await,
            PublicationContract::ExpandUnissuedRange => {
                publication_inode_expansion_reserves_unissued_range(&store).await;
            }
            PublicationContract::RejectIssuedIds => {
                publication_inode_expansion_rejects_issued_ids(&store).await;
            }
        }
    })
    .await;
    // The backend scopes these logical keys to this generated namespace.
    // Exact-value checks ensure cleanup cannot silently race another writer.
    assert!(namespace.starts_with("g12-real-"));
    let records = cleanup.scan_prefix(b"").await.unwrap();
    let checks: Vec<_> = records
        .iter()
        .map(|record| KvCheck {
            key: record.key.clone(),
            expected: Some(record.value.clone()),
        })
        .collect();
    let writes: Vec<_> = records
        .into_iter()
        .map(|record| KvWrite::Delete { key: record.key })
        .collect();
    assert!(cleanup.compare_and_swap(&checks, &writes).await.unwrap());
    assert!(cleanup.scan_prefix(b"").await.unwrap().is_empty());
    outcome.expect("real TiKV publication contract failed");
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_REDIS_URL"]
async fn public_real_redis_g12_same_head_publication_retries_exactly() {
    real_redis_publication_contract(PublicationContract::SameHeadRetry).await;
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_REDIS_URL"]
async fn public_real_redis_g12_inode_expansion_reserves_unissued_range_and_retries() {
    real_redis_publication_contract(PublicationContract::ExpandUnissuedRange).await;
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_REDIS_URL"]
async fn public_real_redis_g12_inode_expansion_rejects_issued_ids() {
    real_redis_publication_contract(PublicationContract::RejectIssuedIds).await;
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_TIKV_PD_ENDPOINTS"]
async fn public_real_tikv_g12_same_head_publication_retries_exactly() {
    real_tikv_publication_contract(PublicationContract::SameHeadRetry).await;
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_TIKV_PD_ENDPOINTS"]
async fn public_real_tikv_g12_inode_expansion_reserves_unissued_range_and_retries() {
    real_tikv_publication_contract(PublicationContract::ExpandUnissuedRange).await;
}

#[tokio::test]
#[ignore = "requires BREWFS_TEST_TIKV_PD_ENDPOINTS"]
async fn public_real_tikv_g12_inode_expansion_rejects_issued_ids() {
    real_tikv_publication_contract(PublicationContract::RejectIssuedIds).await;
}
